version: "3.8"
services:

  phpfpm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: peoplecloud:peoplecloud-php
    container_name: peoplecloud-php-fpm
    volumes:
      - ./:/usr/src/app
    networks:
      - backend
networks:
  backend:

volumes:
  db-data: